Reputation/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('check/', include('check.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

check/urls.py
from django.urls import  path
from . import views

app_name = 'check'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.detail, name='detail'),
    path('ibm/', views.ibm, name='ibm'),
    path('ipvoid/', views.ipvoid, name='ipvoid'),
    path('virustotal/', views.virustotal, name='virustotal'),
    path('iplocation/', views.iplocation, name='iplocation'),
    path('report/', views.report, name='report'),
    path('ibmapi/', views.ibm_api, name='ibmapi'),
    path('virustotalapi/', views.virustotal_api, name='virustotalapi'),
    path('settings/', views.settings, name='settings'),
]

check/models.py
from django.db import models

# Create your models here.

# -----------------------
#   IPADDRESS TABLES
# -----------------------
class Ibm_Ip(models.Model):
    ipadd = models.CharField(max_length=100, primary_key=True)
    score = models.FloatField(max_length=10)
    country = models.CharField(max_length=50)
    category = models.CharField(max_length=200)

class Ipvoid_Ip(models.Model):
    ipadd = models.CharField(max_length=100, primary_key=True)
    score = models.CharField(max_length=10)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)

class IPLocation(models.Model):
    ipadd = models.CharField(max_length=100, primary_key=True)
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    isp = models.CharField(max_length=200)
    lat = models.CharField(max_length=50)
    lon = models.CharField(max_length=50)

# -------------------
#   DOMAIN TABLES
# -------------------
class Ibm_domain(models.Model):
    domain = models.CharField(max_length=100, primary_key=True)
    score = models.CharField(max_length=10)
    country = models.CharField(max_length=50)
    category = models.CharField(max_length=50)

# ------------------
#   URL TABLES
# ------------------
class Ibm_Url(models.Model):
    url = models.CharField(max_length=500, primary_key=True)
    score = models.CharField(max_length=10)
    country = models.CharField(max_length=50)
    category = models.CharField(max_length=50)

class Virus_Total_Url(models.Model):
    url = models.CharField(max_length=200, primary_key=True)
    scan_id = models.CharField(max_length=200)
    score = models.CharField(max_length=10)
    link = models.CharField(max_length=500)
    blacklist = models.CharField(max_length=1000)


# --------------------
#   HASH TABLES
# --------------------
class Ibm_Hash(models.Model):
    hash = models.CharField(max_length=500, primary_key=True)
    family = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    risk = models.CharField(max_length=10)

class Virus_Total_Hash(models.Model):
    hash = models.CharField(max_length=500, primary_key=True)
    scan_id = models.CharField(max_length=500)
    score = models.CharField(max_length=50, default='0')
    md5 = models.CharField(max_length=200)
    sha256 = models.CharField(max_length=200)
    sha1 = models.CharField(max_length=150)
    link = models.CharField(max_length=1000)
    blacklist = models.CharField(max_length=5000)


# -------------------------------
#   FILE SCANS USING VIRUSTOTAL
# -------------------------------
class Virus_Total_Scan(models.Model):
    file = models.CharField(max_length=200, primary_key=True)
    scan_id = models.CharField(max_length=200)
    score = models.CharField(max_length=100)
    md5 = models.CharField(max_length=200)
    sha256 = models.CharField(max_length=200)
    shal = models.CharField(max_length=200)
    blacklist = models.CharField(max_length=5000)
    link = models.CharField(max_length=1000)

# ------------------------
#   IBM X FORCE API KEYS
# ------------------------
class Ibm_API_Credits(models.Model):
    api_key = models.CharField(max_length=200)
    api_password = models.CharField(max_length=200)

# -------------------------
#   VIRUS TOTAL API KEYS
# -------------------------
class Virus_Total_Credits(models.Model):
    apikey = models.CharField(max_length=200)

check/views.py
from django.shortcuts import render
from .Common import ibmxforce, ipvoid_data, iploc, virustotal_data, is_valid_ip,is_valid_domain, is_valid_url
from check.models import Ipvoid_Ip, Ibm_Ip,IPLocation, Ibm_domain, Ibm_Url, Ibm_Hash, Virus_Total_Url, Virus_Total_Hash, Ibm_API_Credits, Virus_Total_Credits
from django.core.files.storage import FileSystemStorage
import csv, os

# =======================
#   INDEX PAGE VIEW
# ========================
def index(request):
    return render(request, 'check/index.html')

# ======================
#   DETAIL PAGE VIEW
# ======================
def detail(request):
    selected_choice = request.POST.get('q')
    if '5' in request.POST.getlist('checks[]'):
        checkbox = ['1', '2', '3', '4']
    else:
        checkbox = request.POST.getlist('checks[]')
    ibm_context, ipv_context, vt_context, loc_context = {}, {}, {}, {}
    # ---------------------------
    #   IBM X FORCE
    # --------------------------
    if '1' in checkbox:
        val = selected_choice.strip()
        if is_valid_ip(val):
            try:
                ibm_db = Ibm_Ip.objects.get(ipadd=val)
                ibm_context['IPADDRESS'], ibm_context['SCORE'], ibm_context['COUNTRY'], ibm_context['CATEGORY'] = ibm_db.ipadd, ibm_db.score, ibm_db.country, ibm_db.category
            except Ibm_Ip.DoesNotExist:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_Ip(ipadd=ibm_context['IPADDRESS'], score=ibm_context['SCORE'], country=ibm_context['COUNTRY'], category=ibm_context['CATEGORY'])
                ibm.save()
        elif is_valid_domain(val):
            try:
                ibm_db = Ibm_domain.objects.get(domain=val)
                ibm_context['DOMAIN'], ibm_context['SCORE'], ibm_context['COUNTRY'], ibm_context['CATEGORY'] = ibm_db.domain, ibm_db.score, ibm_db.country, ibm_db.category
            except:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_domain(domain=ibm_context['DOMAIN'], score=ibm_context['SCORE'], country=ibm_context['COUNTRY'],category=ibm_context['CATEGORY'])
                ibm.save()
        elif is_valid_url(val):
            try:
                ibm_db = Ibm_Url.objects.get(url=val)
                ibm_context['URL'], ibm_context['SCORE'], ibm_context['COUNTRY'], ibm_context['CATEGORY'] = ibm_db.url, ibm_db.score, ibm_db.country, ibm_db.category
            except:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_Url(url=ibm_context['URL'], score=ibm_context['SCORE'], country=ibm_context['COUNTRY'], category=ibm_context['CATEGORY'])
                ibm.save()
        else:
            try:
                ibm_db = Ibm_Hash.objects.get(hash=val)
                ibm_context['HASH'], ibm_context['FAMILY'], ibm_context['TYPE'], ibm_context['RISK'] = ibm_db.hash, ibm_db.family, ibm_db.type, ibm_db.risk
            except Ibm_Hash.DoesNotExist:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_Hash(hash=ibm_context['HASH'], family=ibm_context['FAMILY'], type=ibm_context['TYPE'],risk=ibm_context['RISK'])
                ibm.save()
            except:
                return render(request, 'check/Service_Unavailable.html', {'data':'IBM X Force'})

    # -------------------------
    #   IPVOID SECTION
    # -------------------------
    if '2' in checkbox:
        val = selected_choice.strip()
        if is_valid_ip(val):
            try:
                ipv_db = Ipvoid_Ip.objects.get(ipadd=val)
                ipv_context['IPADDRESS'], ipv_context['SCORE'], ipv_context['COUNTRY'], ipv_context[
                    'CITY'] = ipv_db.ipadd, ipv_db.score, ipv_db.country, ipv_db.city
            except Ipvoid_Ip.DoesNotExist:
                ipv_context = ipvoid_data(ipv_context=ipv_context, mode="single", selected_choice=val)
                ipv = Ipvoid_Ip(ipadd=val, score=ipv_context['SCORE'], country=ipv_context['COUNTRY'],city=ipv_context['CITY'])
                ipv.save()
            except:
                return render(request, 'check/Service_Unavailable.html', {'data':'IPVoid'})

    # --------------------------
    #   IPLOCATION SECTION
    # --------------------------
    if '3' in checkbox:
        val = selected_choice.strip()
        try:
            loc_db = IPLocation.objects.get(ipadd=val)
            loc_context['IPADDRESS'], loc_context['COUNTRY'], loc_context['CITY'], loc_context['REGION'], loc_context[
                'ISP'], loc_context['LATITUDE'], loc_context[
                'LONGITUDE'] = loc_db.ipadd, loc_db.country, loc_db.city, loc_db.region, loc_db.isp, loc_db.lat, loc_db.lon
        except IPLocation.DoesNotExist:
            loc_context = iploc(loc_context=loc_context, mode='single', selected_choice=selected_choice)
            ip_loc = IPLocation(ipadd=loc_context['IPADDRESS'], country=loc_context['COUNTRY'],
                                city=loc_context['CITY'], region=loc_context['REGION'], isp=loc_context['ISP'],
                                lat=loc_context['LATITUDE'], lon=loc_context['LONGITUDE'])
            ip_loc.save()

    # ---------------------
    # VIRUS TOTAL SECTION
    # ---------------------
    if '4' in checkbox:
        val = selected_choice.strip()
        if is_valid_url(val):
            try:
                vt_db = Virus_Total_Url.objects.get(url=val)
                vt_context['URL'], vt_context['SCAN_ID'], vt_context['SCORE'], vt_context['BLACKLIST'], vt_context['LINk'] = vt_db.url, vt_db.scan_id, vt_db.score, vt_db.blacklist, vt_db.link
            except Virus_Total_Url.DoesNotExist:
                vt_context = virustotal_data(vt_context=vt_context, mode='single', selected_choice=val)
                vtotal_db = Virus_Total_Url(url=vt_context['URL'], scan_id=vt_context['SCAN_ID'], score=vt_context['SCORE'], blacklist=vt_context['BLACKLIST'], link=vt_context['LINK'])
                vtotal_db.save()
        else:
            try:
                vt_db = Virus_Total_Hash.objects.get(hash=val)
                vt_context['HASH'], vt_context['SCAN_ID'], vt_context['SCORE'], vt_context['MD5'], vt_context['SHA256'], vt_context['SHA1'], vt_context['LINK'], vt_context['BLACKLIST'] = vt_db.hash, vt_db.scan_id, vt_db.score, vt_db.md5, vt_db.sha256, vt_db.sha1, vt_db.link, vt_db.blacklist
            except Virus_Total_Hash.DoesNotExist:
                try:
                    vt_context = virustotal_data(vt_context=vt_context, mode='single', selected_choice=val)
                    vtotal_db = Virus_Total_Hash(hash=vt_context['HASH'], scan_id=vt_context['SCAN_ID'],score=vt_context['SCORE'], md5=vt_context['MD5'], sha256=vt_context['SHA256'], sha1=vt_context['SHA1'], blacklist=vt_context['BLACKLIST'], link=vt_context['LINK'])
                    vtotal_db.save()
                except:
                    pass

    context = {
        'check':checkbox,
        'ibm':ibm_context,
        'ipv':ipv_context,
        'iploc':loc_context,
        'virustotal':vt_context,
    }
    return render(request, 'check/detail.html', {'reputation':context})



# ===========================
#   IBM X FORCE (check/ibm/)
# ===========================
def ibm(request):
    single = request.POST.get('Singledata')
    bulk = request.POST.get('bulk[]')
    ibm_context, context = {}, {}
    # ---------------------------------------------------
    #   SINGLE DATA CHECK (IPADDRESS, DOMAIN, HASH, URL)
    # ---------------------------------------------------
    if single != None:
        val = single.strip()
        if is_valid_ip(val):
            try:
                ibm_db = Ibm_Ip.objects.get(ipadd=val)
                ibm_context['IPADDRESS'], ibm_context['SCORE'], ibm_context['COUNTRY'], ibm_context['CATEGORY'] = ibm_db.ipadd, ibm_db.score, ibm_db.country, ibm_db.category
            except Ibm_Ip.DoesNotExist:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_Ip(ipadd=ibm_context['IPADDRESS'], score=ibm_context['SCORE'], country=ibm_context['COUNTRY'], category=ibm_context['CATEGORY'])
                ibm.save()
        elif is_valid_domain(val):
            try:
                ibm_db = Ibm_domain.objects.get(domain=val)
                ibm_context['DOMAIN'], ibm_context['SCORE'], ibm_context['COUNTRY'], ibm_context['CATEGORY'] = ibm_db.domain, ibm_db.score, ibm_db.country, ibm_db.category
            except:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_domain(domain=ibm_context['DOMAIN'], score=ibm_context['SCORE'], country=ibm_context['COUNTRY'],category=ibm_context['CATEGORY'])
                ibm.save()
        elif is_valid_url(val):
            try:
                ibm_db = Ibm_Url.objects.get(url=val)
                ibm_context['URL'], ibm_context['SCORE'], ibm_context['COUNTRY'], ibm_context['CATEGORY'] = ibm_db.url, ibm_db.score, ibm_db.country, ibm_db.category
            except:
                ibm_context = ibmxforce(ibm_context=ibm_context, mode="single", selected_choice=val)
                ibm = Ibm_Url(url=ibm_context['URL'], score=ibm_context['SCORE'], country=ibm_context['COUNTRY'], category=ibm_context['CATEGORY'])
                ibm.save()
        else:
            try:
                ibm_db = Ibm_Hash.objects.get(hash=val)
                ibm_context['HASH'], ibm_context['FAMILY'], ibm_context['TYPE'], ibm_context['RISK'] = ibm_db.hash, ibm_db.family, ibm_db.type, ibm_db.risk
            except Ibm_Hash.DoesNotExist:

check/templates/check/detail.html
{% extends 'check/base.html' %}
{% load myfilters %}

<!-- NAVIGATION BAR -->
{% block nav %}
<ul class="nav navbar-nav">
    <li><a href="{%url 'check:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
    <li><a href="{%url 'check:ibm' %}">IBMXForce</a> </li>
    <li><a href="{%url 'check:ipvoid' %}">IPVoid</a> </li>
    <li><a href="{%url 'check:virustotal' %}">Virus Total</a> </li>
    <li><a href="{%url 'check:iplocation' %}">IPLocation</a> </li>
</ul>
<ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'check:report' %}"><span class="glyphicon glyphicon-file"></span> Report</a></li>
    <li><a href="{%url 'check:settings' %}"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
</ul>
{% endblock %}

<!-- BODY CONTENT -->
{% block content %}
<br>
<div class="container">

    <!-- HEADER CONTENT -->
    <div class="jombroton text-center">
        <h1>Quick Check</h1>
        <h4>IPAddress / Domain / Url / Hash</h4>

        <!-- FORM DATA TO CHECK THE MALICIOUS ACTIVITY OF IPADDRESS / DOMAIN / URL / HASH -->
        <form action="{%url 'check:detail'%}" class="form-inline" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="q" class="form-control">
                <button type="submit" class="btn btn-warning">Check</button>
            </div>
            <br><br>
            <div class="checkbox">
                <label><input type="checkbox" name="checks[]" value="1"> IBMXForce</label>
                <label><input type="checkbox" name="checks[]" value="2"> IPVoid</label>
                <label><input type="checkbox" name="checks[]" value="3"> IPLocation</label>
                <label><input type="checkbox" name="checks[]" value="4"> VirusTotal</label>
                <label><input type="checkbox" name="checks[]" value="5"> All Websites</label>
          </div>
        </form>
    </div>
</div>
<br><br>

<!-- RESULT FOR THE GIVEN DATA (IPADDRESS / DOMAIN / URL / HASH) -->
    <div class="container">
        <div class="row">

            <!-- RESULT FOR IBM -->
            {% if reputation.ibm.items|is_len %}
                {% if '1' in reputation.check %}
                    <div class="col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">IBMXForce</div>
                                <div class="panel-body">
                                    <table class="table table-bordered">
                                        <tbody>
                                        {% for key, value in reputation.ibm.items %}
                                        <tr>
                                           <td>{{ key }}</td><td>{{ value }}</td>
                                            {% if key == 'SCORE' and value|ifinlist:"0, 1, 2, 3, 4" %}
                                                <span><button type="button" class="btn btn-success">Safe</button> </span>
                                            {% elif key == 'SCORE' and value|ifinlist:"5, 6, 7, 8, 9, 10" %}
                                                <span><button type="button" class="btn btn-danger">Malicious</button> </span>
                                            {% endif %}
                                            {% if key == 'RISK' and value|is_risk %}
                                                <span><button type="button" class="btn btn-danger">Malicious</button> </span>
                                            {% elif key == 'RISK' %}
                                                <span><button type="button" class="btn btn-success">Safe</button> </span>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}

            <!-- RESULTS FOR IPVOID -->
            {% if reputation.ipv.items|is_len %}
                {% if '2' in reputation.check %}
                    <div class="col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">IPVoid</div>
                                <div class="panel-body">
                                    <table class="table table-bordered">
                                        <tbody>
                                        {% for key, value in reputation.ipv.items %}
                                        <tr>
                                           <td>{{ key }}</td><td>{{ value }}</td>
                                            {% if key == 'SCORE' and value|ifinlist:"0, 1, 2, 3, 4, 5"%}
                                                <span><button type="button" class="btn btn-success">Safe</button> </span>
                                            {% elif key == 'SCORE' %}
                                                <span><button type="button" class="btn btn-danger">Malicious</button> </span>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}

            <!-- RESULTS FOR IPLOCATION -->
            <div class="row">
            {% if reputation.iploc.items|is_len %}
                {% if '3' in reputation.check %}
                    <div class="col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">IPLocation</div>
                            <div class="panel-body">
                                <table class="table table-bordered">
                                    <tbody>
                                    {% for key, value in reputation.iploc.items %}
                                    <tr>
                                       <td>{{ key }}</td><td>{{ value }}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}

                <!-- RESULTS FOR VIRUSTOTAL -->
            {% if reputation.virustotal.items|is_len %}
                {% if '4' in reputation.check %}
                <div class="col-md-6">
                    <div class="panel panel-primary" style="overflow:auto">
                        <div class="panel-heading">VirusTotal</div>
                        <div class="panel-body">
                            <table class="table table-bordered">
                                <tbody>
                                {% for key, value in reputation.virustotal.items %}
                                <tr>
                                    <td>{{ key }}</td>
                                    {% if key == 'SCORE' and value|check_score %}
                                        <span><button class="btn btn-danger">Malicious</button> </span>
                                    {% elif key == 'SCORE' %}
                                        <span><button class="btn btn-success">Safe</button> </span>
                                    {% endif %}
                                    {% if key == 'LINK'%}
                                        <td><a href='{{ value }}'>Link To VirusTotal</a></td>
                                    {%else%}
                                     <td>{{ value }}</td>
                                    {% endif %}
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

check/templates/check/index.html
{% extends 'check/base.html' %}
    {% block nav %}
    <ul class="nav navbar-nav">
        <li class="active"><a href="{%url 'check:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{%url 'check:ibm' %}">IBMXForce</a> </li>
        <li><a href="{%url 'check:ipvoid' %}">IPVoid</a> </li>
        <li><a href="{%url 'check:virustotal' %}">Virus Total</a> </li>
        <li><a href="{%url 'check:iplocation' %}">IPLocation</a> </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{%url 'check:report' %}"><span class="glyphicon glyphicon-file"></span> Report</a></li>
        <li><a href="{%url 'check:settings' %}"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
    </ul>
    {% endblock %}
    {% block content %}
    <div class="container">
        <div class="jumborton">
            <h1>Threat Verifica</h1>
            <p>Check the Malicious IPAddress, Domains, Urls, Hashes and File Scan from Popular Website</p>
            <img src="http://www.appincoimbatore.com/reimages/appin-information-security.jpg" width="1080px" height="300px">
        </div>
    </div>
    <br>
    <div class="container">
        <form action="{%url 'check:detail' %}" method="post">
            {% csrf_token %}
          <div class="form-group">
            <label for="data">Enter IPAddress / Domain / Url / Hash</label>
            <input type="text" class="form-control" id="data" name="q">
          </div>
          <div class="checkbox">
            <label><input type="checkbox" name="checks[]" value="1"> IBMXForce</label>
            <label><input type="checkbox" name="checks[]" value="2"> IPVoid</label>
            <label><input type="checkbox" name="checks[]" value="3"> IPLocation</label>
            <label><input type="checkbox" name="checks[]" value="4"> VirusTotal</label>
            <label><input type="checkbox" name="checks[]" value="5"> All Websites</label>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

check/templates/check/settings.html
{% extends 'check/base.html' %}

<!-- NAVIGATION BAR -->
{% block nav %}
<ul class="nav navbar-nav">
    <li><a href="{%url 'check:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
    <li><a href="{%url 'check:ibm' %}">IBMXForce</a></li>
    <li><a href="{%url 'check:ipvoid' %}">IPVoid</a></li>
    <li><a href="{%url 'check:virustotal' %}">Virus Total</a></li>
    <li><a href="{%url 'check:iplocation' %}">IPLocation</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
    <li><a href="{%url 'check:report' %}"><span class="glyphicon glyphicon-file"></span> Report</a></li>
    <li class="active"><a href="{%url 'check:settings' %}"><span class="glyphicon glyphicon-cog"></span> Settings</a>
    </li>
</ul>
{% endblock %}

<!-- BODY CONTENT -->
{% block content %}
<div class="container">

    <!-- PAGE HEADING -->
    <div class="jomborton">
        <h2>Add API Keys! Start Work</h2>
        <p>Get Public API Keys from IBMXForce and VirusTotal</p>
        <button class="btn btn-warning"><a href="https://exchange.xforce.ibmcloud.com/" target="_blank" style="color:white;text-decoration:none;">Get IBM API Keys</a> </button>
        <button class="btn btn-warning"><a href="https://www.virustotal.com/#/home/upload" target="_blank" style="color:white;text-decoration:none;">Get Virus Total API Keys</a> </button>
    </div>
    <br>

    <!-- DISPLAY POPUP FOR CONFORMATION OF IBM AND VIRUSTOTAL KEYS STORE IN DATABASE-->
    {% for key, value in alert.items %}
        {% if value == "True" %}
            <script>alert('API KEYs Stored in Database Successfully')</script>
        {% endif %}
    {% endfor %}
    <div class="row">

        <!-- FROM TO STORE THE API KEYS OF IBM X FORCE  -->
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">IBM X Force API Keys</div>
                <div class="panel-body">
                    <button type="button" class="btn btn-danger">Warning : Public API Key has a Limit of 5000 API Calls / Month</button>
                    <br/><br/>
                    <form method="post" action="{%url 'check:ibmapi' %}">{% csrf_token %}
                        <div class="form-group">
                            <label for="key">Enter API Key</label><br/>
                            <input type="password" name="apikey" class="form-control" value="" id="key">
                            <br/>
                        </div>
                        <div class="form-group">
                            <label for="val">Enter API Password</label><br/>
                            <input type="password" name="apipass" class="form-control" value="" id="val"><br/>
                        </div>
                        <script>
                            function myFunction1() {
                              var x = document.getElementById("key");
                              var y = document.getElementById("val");
                              if (x.type === "password" && y.type == "password") {
                                x.type = "text";
                                y.type = "text";
                              } else {
                                x.type = "password";
                                y.type = "password";
                              }
                            }
                        </script>
                        <div class="checkbox">
                            <label><input type="checkbox" onclick="myFunction1()"> show keys</label>
                            <label><input type="checkbox" name="ibm"> Add to Database</label>
                        </div>
                        <button type="submit" class="btn btn-success">Add Keys</button>
                    </form>
                </div>
            </div>
        </div>

        <!-- FORM TO STORE THE API KEYS OF VIRUSTOTAL -->
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">Virus Total API Key</div>
                <div class="panel-body">
                    <button type="button" class="btn btn-danger">Warning : Public API Keys has a limit of 4 API Calls / Minute</button>
                    <br/><br/>
                    <form method="post" action="{%url 'check:virustotalapi' %}">{% csrf_token %}
                        <div class="from-group">
                            <label for="vkey">Enter API Key</label><br/>
                            <input type="password" class="form-control" name="virustotal_api_key" id="vkey">
                        </div>
                        <script>
                            function myFunction2() {
                              var x = document.getElementById("vkey");
                              if (x.type === "password") {
                                x.type = "text";
                              } else {
                                x.type = "password";
                              }
                            }
                        </script>
                        <div class="checkbox">
                            <label><input type="checkbox" onclick="myFunction2()"> Show Key</label>
                            <label><input type="checkbox" name="virustotal"> Add to Database</label>
                        </div>
                        <button type="submit" class="btn btn-success">Add Key</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}